Education
Bentley912/cap_app pull request #17
Opened 2018-04-14 16:58 UTC by lee2smooth03

Hey Patrick, can you review these?
I need to practice on my machine

2018-04-17 01:52 UTC, Bentley912 requested changes
Thanks for this. There are some small changes to the code including Title of the page. Right now, is it saving to sessionStorage? Was it verified that we are saving it somewhere?

2018-04-17 01:52 UTC, Bentley912 commented on public/index.html
>                <legend>Demographic Info</legend>
Change Title to Appropriate Title Please

2018-04-17 01:52 UTC, Bentley912 commented on public/js/education.js
> +$(document).ready(function(){
You didn't need to create a new JS file. Simply change the button and add it to the form JS

2018-04-17 01:52 UTC, Bentley912 commented on public/js/form.js
>      })
What did you do here?

2018-04-17 01:52 UTC, Bentley912 commented on public/js/education.js
> +    $('.eduForm').submit(function(){
You dont need this code if you are using the saveData() function.

2018-04-19 21:39 UTC, Bentley912 approved these changes

2018-04-19 21:40 UTC, Bentley912 requested changes
Didnt mean to Approve. Previous Changes still need to happen.

2018-04-19 21:54 UTC, lee2smooth03 commented
Ok...I got red letters in my terminal last time I ran node server.js

On Apr 19, 2018 5:40 PM, "Patrick Bentley" <notifications@github.com> wrote:

*@Bentley912* requested changes on this pull request.

Didnt mean to Approve. Previous Changes still need to happen.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Bentley912/cap_app/pull/17#pullrequestreview-113787202>,
or mute the thread
<https://github.com/notifications/unsubscribe-auth/AZmqb4K0hc7PUQGicxdNWGK9v0h9Tfnwks5tqQQ4gaJpZM4TVJBr>
.

2018-05-20 11:11 UTC, closed without merging